
# Params for features
feature_type: SIFT            # Feature type (SURF, SIFT)
feature_min_frames: 5000      # If fewer frames are detected, sift_peak_threshold/surf_hessian_threshold is reduced.
feature_process_size: 2048    # Resize the image if its size is larger than specified. Set to -1 for original size

# Params for SIFT
sift_peak_threshold: 0.04     # Smaller value -> more features
sift_edge_threshold: 10       # See OpenCV doc

# Params for SURF
surf_hessian_threshold: 3000  # Smaller value -> more features
surf_n_octaves: 4             # See OpenCV doc
surf_n_octavelayers: 2        # See OpenCV doc

# Masks for regions that will be ignore for feature extraction
# List of bounding boxes specified as the ratio with respect to the height and width
# [top_left_x, top_left_y, bottom_right_x, bottom_right_y] where x, y refer to
# vertical/horizontal dimension of an image
# masks: [[0.96, 0.0, 1.0, 0.15], [0,0.95,0.05,1]]

# Params for general matching
lowes_ratio: 0.6              # Ratio test for matches

# Params for FLANN matching
flann_branching: 16           # See OpenCV doc
flann_iterations: 10          # See OpenCV doc
flann_checks: 100             # Smaller -> Faster (but might lose good matches)

# Params for preemtive matching
matching_gps_distance: 150            # Maximum gps distance between two images for matching
preemptive_max: 200                   # Number of features to use for preemptive matching
preemptive_threshold: 4               # If number of matches passes the threshold -> full feature matching
preemptive_matching_gps_distance: 300 # Maximum gps distance between two images for preemptive matching

# Params for geometric estimation
robust_matching_threshold: 3          # Outlier threshold (in pixels) for fundamental matrix estimation
robust_matching_min_match: 20         # Minimum number of matches to be considered as an edge in the match grph
five_point_algo_threshold: 5          # Outlier threshold (in pixels) for essential matrix estimation
five_point_algo_min_inliers: 20       # Minimum number of inliers for considering a two view reconstruction valid.
triangulation_threshold: 5            # Outlier threshold (in pixels) for accepting a triangulated point.
resection_threshold: 5                # Outlier threshold (in pixels) for camera resection.
resection_min_inliers: 10             # Minimum number of resection inliers to accept it.

# Params for track creation
min_track_length: 2           # Minimum number of features/images per track

# Params for bundle adjustment
loss_function: TruncatedLoss  # Loss function for the ceres problem (see: http://ceres-solver.org/modeling.html#lossfunction)
loss_function_threshold: 5.0  # Usually cost is quadratic for smaller residuals and sub-quadratic above.
exif_focal_sd: 0.01           # The standard deviation of the diff between the focal length and the exif focal length in width units.
bundle_interval: 2            # bundle adjustment after adding 'bundle_interval' cameras


# Other params
processes: 1                  # Number of threads to use
